#!/bin/sh
set -e

if [ "$1" = "configure" ] || [ "$1" = "abort-upgrade" ]; then
    update-alternatives --install /usr/bin/x-www-browser \
        x-www-browser /opt/3WebsBrowser/3websbrowser 80
    chown root /opt/3WebsBrowser/chrome-sandbox
    chmod 4755 /opt/3WebsBrowser/chrome-sandbox
    echo "Run sudo xdg-settings set default-web-browser 3websbrowser.desktop && sudo update-alternatives --config x-www-browser to set as default browser."
    ln -sf /opt/Min/3websbrowser /usr/bin/3websbrowser
fi
